import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[env]
term = "xterm-256color"

[font]
size = 12

[font.normal]
family = "GoMono Nerd Font"

[window]
decorations = "none"
startup_mode = "Maximized"

[scrolling]
history = 20000
multiplier = 5

#[cursor]
#style = { shape = "Beam", blinking = "Always" }
#blink_interval = 750

