[language-server.clangd]
command = "clangd"
args = ["--header-insertion=never"]

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
file-types = ["c", "h"]
auto-format = false

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
